# Generated by Django 5.2.1 on 2025-07-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestProject1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
